config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :pro_peds
  resources :locals
  resources :tipo_trabajadors
  resources :pedidos
  resources :trabajadors
  resources :stocks
  resources :ins_pros
  resources :clientes
  resources :insumos
  resources :estados
  resources :productos
  resources :tipo_productos
  root 'page#index'
  get 'page/auditoria'
  get 'page/mtb'
  get 'page/procedimiento'
  get 'page/reporte'
  get 'page/vista'
  post 'page/mtb'
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :cliente
  has_one :trabajador
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  attribute :rol, :string, default: "cli"

  after_create :crearcliente

  def crearcliente
    if (self.rol == nil || self.rol == "cli" )
      @clie =Cliente.create(cli_nomb: "Nombre", cli_pass: self.password, account_id:self.id)
      @clie.save
    end
  end
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :pedido, :foreign_key => :ped_clie, :primary_key => :cli_id
  belongs_to :account
end

app/models/estado.rb
class Estado < ApplicationRecord
  has_many :pedido, :foreign_key => :ped_esta, :primary_key => :est_id
end

app/models/ins_pro.rb
class InsPro < ApplicationRecord
  belongs_to :producto, :foreign_key => :inpr_prod, :primary_key => :pro_id
  belongs_to :insumo, :foreign_key => :inpr_insu, :primary_key => :ins_id
end

app/models/insumo.rb
class Insumo < ApplicationRecord
  has_many :ins_pro, :foreign_key => :inpr_insu, :primary_key => :ins_id
  has_many :stock, :foreign_key => :sto_insu, :primary_key => :ins_id
end

app/models/local.rb
class Local < ApplicationRecord
  self.table_name = "pizzeria"
  has_many :stock, :foreign_key => :sto_pizz, :primary_key => :piz_id
  has_many :trabajador, :foreign_key => :tra_pizz, :primary_key => :piz_id
  has_many :pedido, :foreign_key => :ped_pizz, :primary_key => :piz_id


end

app/models/medida.rb
class Medida < ApplicationRecord
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :estado, :foreign_key => :ped_esta, :primary_key => :est_id
  belongs_to :local, :foreign_key => :ped_pizz, :primary_key => :piz_id
  belongs_to :trabajador, :foreign_key => :ped_trab, :primary_key => :tra_rut
  belongs_to :cliente, :foreign_key => :ped_clie,  :primary_key => :cli_id
  has_many :pro_ped, :foreign_key => :prpe_pedi, :primary_key => :ped_id, dependent: :destroy, inverse_of: :pedido

  accepts_nested_attributes_for :pro_ped, allow_destroy: true, reject_if: ->(attrs) { attrs['prpe_cant'].blank? || attrs['prpe_prod'].blank? }
end

app/models/pro_ped.rb
class ProPed < ApplicationRecord
  belongs_to :producto, :foreign_key => :prpe_prod, :primary_key => :pro_id
  belongs_to :pedido, :foreign_key => :prpe_pedi, :primary_key => :ped_id
end

app/models/producto.rb
class Producto < ApplicationRecord
  belongs_to :tipo_producto, :foreign_key => :pro_tpro, :primary_key => :tpro_id
  has_many :ins_pro, :foreign_key => :inpr_prod, :primary_key => :pro_id, dependent: :destroy, inverse_of: :producto
  has_many :pro_ped, :foreign_key => :prpe_prod, :primary_key => :pro_id

  #accepts_nested_attributes_for :ins_pro, :reject_if => lambda { |b| b[:inpr_insu].blank? }
  accepts_nested_attributes_for :ins_pro, allow_destroy: true, reject_if: ->(attrs) { attrs['inpr_cant'].blank? || attrs['inpr_insu'].blank? }
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :insumo, :foreign_key => :sto_insu, :primary_key => :ins_id
  belongs_to :pizzeria, :foreign_key => :sto_pizz, :primary_key => :piz_id
end

app/models/tipo_producto.rb
class TipoProducto < ApplicationRecord
  has_many :producto, :foreign_key => :pro_tpro, :primary_key => :tpro_id
end

app/models/trabajador.rb
class Trabajador < ApplicationRecord
  belongs_to :local, :foreign_key => :tra_pizz, :primary_key => :piz_id
  belongs_to :tipo_trabajador, :foreign_key => :tra_ttra, :primary_key => :ttra_id
  has_many :pedido, :foreign_key => :ped_trab, :primary_key => :tra_rut
  belongs_to :account

  validates :tra_rut, uniqueness: true

  before_validation :crearcuenta

  def crearcuenta
    @trabemail= self.tra_nomb+"@pizzacto.cl"
    @acctrab = Account.create(email: @trabemail, password: "password")
    self.account_id = @acctrab.id
  end
end

app/models/v_ins_local.rb
class VInsLocal < ApplicationRecord
end

app/models/v_ven_total.rb
class VVenTotal < ApplicationRecord
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  def create
    @cliente = Cliente.new(cliente_params)

    if @cliente.save
      redirect_to @cliente, notice: 'Cliente was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /clientes/1
  def update
    if @cliente.update(cliente_params)
      redirect_to @cliente, notice: 'Cliente was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /clientes/1
  def destroy
    @cliente.destroy
    redirect_to clientes_url, notice: 'Cliente was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cliente_params
      params.require(:cliente).permit(:cli_nomb, :cli_appa, :cli, :cli_rut, :cli_pass)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/insumos_helper.rb
module InsumosHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/clientes/_form.html.erb
<%= form_with(model: cliente, local: true) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field col s12 m6 l4">
    <%= form.label :cli_nomb %>
    <%= form.text_field :cli_nomb, id: :cliente_cli_nomb %>
  </div>

  <div class="input-field col s12 m6 l4">
    <%= form.label :cli_appa %>
    <%= form.text_field :cli_appa, id: :cliente_cli_appa %>
  </div>

  <div class="input-field col s12 m6 l4">
    <%= form.label :cli %>
    <%= form.text_field :cli, id: :cliente_cli %>
  </div>

  <div class="input-field col s12 m6 l4">
    <%= form.label :cli_rut %>
    <%= form.text_field :cli_rut, id: :cliente_cli_rut %>
  </div>

  <div class="input-field col s12 m6 l4">
    <%= form.label :cli_pass %>
    <%= form.text_field :cli_pass, id: :cliente_cli_pass %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<div class="card hoverable">
  <div class="card-image">
    <img src=<%= image_url('c2.jpg') %> >
    <span class="card-title">Cliente</span>
  </div>
</div>

<div class="card hoverable">
  <div class="card-content">
<%= render 'form', cliente: @cliente %>
</div>
</div>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Cli nomb</th>
      <th>Cli appa</th>
      <th>Cli</th>
      <th>Cli rut</th>
      <th>Cli pass</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.cli_nomb %></td>
        <td><%= cliente.cli_appa %></td>
        <td><%= cliente.cli %></td>
        <td><%= cliente.cli_rut %></td>
        <td><%= cliente.cli_pass %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to '<i class="material-icons">mode_edit</i>'.html_safe, edit_cliente_path(cliente) %></td>
        <td><%= link_to '<i class="material-icons">delete</i>'.html_safe, cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cli nomb:</strong>
  <%= @cliente.cli_nomb %>
</p>

<p>
  <strong>Cli appa:</strong>
  <%= @cliente.cli_appa %>
</p>

<p>
  <strong>Cli:</strong>
  <%= @cliente.cli %>
</p>

<p>
  <strong>Cli rut:</strong>
  <%= @cliente.cli_rut %>
</p>

<p>
  <strong>Cli pass:</strong>
  <%= @cliente.cli_pass %>
</p>

<%= link_to '<i class="material-icons">mode_edit</i>'.html_safe, edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>