config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :pro_peds
  resources :locals
  resources :tipo_trabajadors
  resources :pedidos
  resources :trabajadors
  resources :stocks
  resources :ins_pros
  resources :clientes
  resources :insumos
  resources :estados
  resources :productos
  resources :tipo_productos
  root 'page#index'
  get 'page/auditoria'
  get 'page/mtb'
  get 'page/procedimiento'
  get 'page/reporte'
  get 'page/vista'
  post 'page/mtb'
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :cliente
  has_one :trabajador
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  attribute :rol, :string, default: "cli"

  after_create :crearcliente

  def crearcliente
    if (self.rol == nil || self.rol == "cli" )
      @clie =Cliente.create(cli_nomb: "Nombre", cli_pass: self.password, account_id:self.id)
      @clie.save
    end
  end
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :pedido, :foreign_key => :ped_clie, :primary_key => :cli_id
  belongs_to :account
end

app/models/estado.rb
class Estado < ApplicationRecord
  has_many :pedido, :foreign_key => :ped_esta, :primary_key => :est_id
end

app/models/ins_pro.rb
class InsPro < ApplicationRecord
  belongs_to :producto, :foreign_key => :inpr_prod, :primary_key => :pro_id
  belongs_to :insumo, :foreign_key => :inpr_insu, :primary_key => :ins_id
end

app/models/insumo.rb
class Insumo < ApplicationRecord
  has_many :ins_pro, :foreign_key => :inpr_insu, :primary_key => :ins_id
  has_many :stock, :foreign_key => :sto_insu, :primary_key => :ins_id
end

app/models/local.rb
class Local < ApplicationRecord
  self.table_name = "pizzeria"
  has_many :stock, :foreign_key => :sto_pizz, :primary_key => :piz_id
  has_many :trabajador, :foreign_key => :tra_pizz, :primary_key => :piz_id
  has_many :pedido, :foreign_key => :ped_pizz, :primary_key => :piz_id


end

app/models/medida.rb
class Medida < ApplicationRecord
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :estado, :foreign_key => :ped_esta, :primary_key => :est_id
  belongs_to :local, :foreign_key => :ped_pizz, :primary_key => :piz_id
  belongs_to :trabajador, :foreign_key => :ped_trab, :primary_key => :tra_rut
  belongs_to :cliente, :foreign_key => :ped_clie,  :primary_key => :cli_id
  has_many :pro_ped, :foreign_key => :prpe_pedi, :primary_key => :ped_id, dependent: :destroy, inverse_of: :pedido

  accepts_nested_attributes_for :pro_ped, allow_destroy: true, reject_if: ->(attrs) { attrs['prpe_cant'].blank? || attrs['prpe_prod'].blank? }
end

app/models/pro_ped.rb
class ProPed < ApplicationRecord
  belongs_to :producto, :foreign_key => :prpe_prod, :primary_key => :pro_id
  belongs_to :pedido, :foreign_key => :prpe_pedi, :primary_key => :ped_id
end

app/models/producto.rb
class Producto < ApplicationRecord
  belongs_to :tipo_producto, :foreign_key => :pro_tpro, :primary_key => :tpro_id
  has_many :ins_pro, :foreign_key => :inpr_prod, :primary_key => :pro_id, dependent: :destroy, inverse_of: :producto
  has_many :pro_ped, :foreign_key => :prpe_prod, :primary_key => :pro_id

  #accepts_nested_attributes_for :ins_pro, :reject_if => lambda { |b| b[:inpr_insu].blank? }
  accepts_nested_attributes_for :ins_pro, allow_destroy: true, reject_if: ->(attrs) { attrs['inpr_cant'].blank? || attrs['inpr_insu'].blank? }
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :insumo, :foreign_key => :sto_insu, :primary_key => :ins_id
  belongs_to :pizzeria, :foreign_key => :sto_pizz, :primary_key => :piz_id
end

app/models/tipo_producto.rb
class TipoProducto < ApplicationRecord
  has_many :producto, :foreign_key => :pro_tpro, :primary_key => :tpro_id
end

app/models/tipo_trabajador.rb
class TipoTrabajador < ApplicationRecord
  has_many :trabajador, :foreign_key => :tra_ttra, :primary_key => :ttra_id

  validates :ttra_id, uniqueness: true
end

app/models/trabajador.rb
class Trabajador < ApplicationRecord
  belongs_to :local, :foreign_key => :tra_pizz, :primary_key => :piz_id
  belongs_to :tipo_trabajador, :foreign_key => :tra_ttra, :primary_key => :ttra_id
  has_many :pedido, :foreign_key => :ped_trab, :primary_key => :tra_rut
  belongs_to :account

  validates :tra_rut, uniqueness: true

  before_validation :crearcuenta

  def crearcuenta
    @trabemail= self.tra_nomb+"@pizzacto.cl"
    @acctrab = Account.create(email: @trabemail, password: "password")
    self.account_id = @acctrab.id
  end
end

app/models/v_ins_local.rb
class VInsLocal < ApplicationRecord
end

app/models/v_ven_total.rb
class VVenTotal < ApplicationRecord
end

app/controllers/locals_controller.rb
class LocalsController < ApplicationController
  before_action :set_local, only: [:show, :edit, :update, :destroy]

  # GET /locals
  def index
    @locals = Local.all
    @local = Local.new
  end

  # GET /locals/1
  def show
    @trab = @local.trabajador
  end

  # GET /locals/new
  def new
    @local = Local.new
  end

  # GET /locals/1/edit
  def edit
  end

  # POST /locals
  def create
    @local = Local.new(local_params)

    if @local.save
      redirect_to locals_url, notice: 'Local was successfully created.'
    else
      redirect_to locals_url, notice: 'Local no pudo ser creado.'
    end
  end

  # PATCH/PUT /locals/1
  def update
    if @local.update(local_params)
      redirect_to locals_url, notice: 'Local was successfully updated.'
    else
      redirect_to locals_url, notice: 'Local no pudo ser editado.'
    end
  end

  # DELETE /locals/1
  def destroy
    @local.destroy
    redirect_to locals_url, notice: 'Local was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local
      @local = Local.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def local_params
      params.require(:local).permit(:piz_nomb, :piz_dire, :piz_tele)
    end
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/insumos_helper.rb
module InsumosHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/locals/_form.html.erb
<%= form_with(model: local, local: true) do |form| %>
  <% if local.errors.any? %>
    <% local.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
  
<div class="row">
  <div class="input-field col s12 m6 l4">
    <%= form.label :piz_nomb, "Nombre Pizzeria" %>
    <%= form.text_field :piz_nomb, id: :local_piz_nomb %>
  </div>

  <div class="input-field col s12 m6 l4">
    <%= form.label :piz_tele, "Telefono"  %>
    <%= form.number_field :piz_tele, id: :local_piz_tele %>
  </div>

  <div class="input-field col s12 m6 l6">
    <%= form.label :piz_dire, "Direccion" %>
    <%= form.text_field :piz_dire, id: :local_piz_dire %>
  </div>
</div>

  <div class="row">
    <button class="btn waves-effect waves-light" type="submit" name="action">Enviar
      <i class="material-icons right">send</i>
    </button>
  </div>

<% end %>

app/views/locals/edit.html.erb
<div class="card hoverable">
  <div class="card-image">
    <img src=<%= image_url('c2.jpg') %> >
    <span class="card-title"><%= @local.piz_nomb %></span>
  </div>
</div>
<div class="card hoverable">
  <div class="card-content">
    <%= render 'form', local: @local %>
  </div>
</div>

app/views/locals/index.html.erb
<div class="card hoverable">
  <div class="card-image">
    <img src=<%= image_url('c2.jpg') %> >
    <span class="card-title">Pizzerias</span>
  </div>
</div>

<ul class="collapsible popout" data-collapsible="accordion">
  <li>
    <div class="collapsible-header"><i class="material-icons">av_timer</i>Agregar Pizzeria</div>
    <div class="collapsible-body hoverable">
      <%= render 'form', local: @local %>
    </div>
  </li>
  <li>
    <div class="collapsible-header"><i class="material-icons">business</i>Pizzerias</div>
    <div class="collapsible-body hoverable">
      <table class="bordered highlight">
  <thead>
    <tr>
      <th class="width 20%">Nombre Local</th>
      <th class="width 40%">Direccion</th>
      <th class="width 20%">Telefono</th>
      <th class="width 20%"> </th>
    </tr>
  </thead>

  <tbody>
    <% @locals.each do |local| %>
      <tr>
        <td><%= local.piz_nomb %></td>
        <td><%= local.piz_dire %></td>
        <td><%= local.piz_tele %></td>
        <td><%= link_to '<i class="material-icons">subtitles</i>'.html_safe, local %>
          <%= link_to '<i class="material-icons">mode_edit</i>'.html_safe, edit_local_path(local) %>
          <%= link_to '<i class="material-icons">delete</i>'.html_safe, local, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</li>
</ul>

<script>
$(document).ready(function(){
    $('.collapsible').collapsible();
});
</script>

app/views/locals/new.html.erb
<h1>New Local</h1>

<%= render 'form', local: @local %>

<%= link_to 'Back', locals_path %>

app/views/locals/show.html.erb
<div class="card hoverable">
  <div class="card-image">
    <img src=<%= image_url('c2.jpg') %> >
    <span class="card-title"><%= @local.piz_nomb %></span>
  </div>
</div>


<div class="card hoverable">
  <div class="card-content">
    <p>
      <strong>Nombre:</strong>
      <%= @local.piz_nomb %>
    </p>

    <p>
      <strong>Direccion:</strong>
      <%= @local.piz_dire %>
    </p>

    <p>
      <strong>Telefono:</strong>
      <%= @local.piz_tele %>
    </p>

  </div>
</div>

<ul class="collapsible popout" data-collapsible="accordion">
  <li>
  <div class="collapsible-header"><i class="material-icons">person_pin</i>Empleados</div>
  <div class="collapsible-body hoverable">
    <table class="bordered highlight">
      <thead>
        <tr>
          <th class="width 25%">Nombre Completo</th>
          <th class="width 25%">Local</th>
          <th class="width 25%">Tipo Trabajador</th>
          <th class="width 25%"> </th>
        </tr>
      </thead>
      <tbody>
        <% @trab.each do |t| %>
          <tr>
            <td><%= t.tra_nomb+" "+t.tra_appa+" "+t.tra_apma %></td>
            <td><%= t.local.piz_nomb %></td>
            <td><%= t.tipo_trabajador.ttra_desc %></td>
            <td><%= link_to '<i class="material-icons">mode_edit</i>'.html_safe, edit_trabajador_path(t) %>
              <%= link_to '<i class="material-icons">delete</i>'.html_safe, t, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</li>
</ul>