config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :pro_peds
  resources :locals
  resources :tipo_trabajadors
  resources :pedidos
  resources :trabajadors
  resources :stocks
  resources :ins_pros
  resources :clientes
  resources :insumos
  resources :estados
  resources :productos
  resources :tipo_productos
  root 'page#index'
  get 'page/auditoria'
  get 'page/mtb'
  get 'page/procedimiento'
  get 'page/reporte'
  get 'page/vista'
  post 'page/mtb'
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :cliente
  has_one :trabajador
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  attribute :rol, :string, default: "cli"

  after_create :crearcliente

  def crearcliente
    if (self.rol == nil || self.rol == "cli" )
      @clie =Cliente.create(cli_nomb: "Nombre", cli_pass: self.password, account_id:self.id)
      @clie.save
    end
  end
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :pedido, :foreign_key => :ped_clie, :primary_key => :cli_id
  belongs_to :account
end

app/models/estado.rb
class Estado < ApplicationRecord
  has_many :pedido, :foreign_key => :ped_esta, :primary_key => :est_id
end

app/models/ins_pro.rb
class InsPro < ApplicationRecord
  belongs_to :producto, :foreign_key => :inpr_prod, :primary_key => :pro_id
  belongs_to :insumo, :foreign_key => :inpr_insu, :primary_key => :ins_id
end

app/models/insumo.rb
class Insumo < ApplicationRecord
  has_many :ins_pro, :foreign_key => :inpr_insu, :primary_key => :ins_id
  has_many :stock, :foreign_key => :sto_insu, :primary_key => :ins_id
end

app/models/local.rb
class Local < ApplicationRecord
  self.table_name = "pizzeria"
  has_many :stock, :foreign_key => :sto_pizz, :primary_key => :piz_id
  has_many :trabajador, :foreign_key => :tra_pizz, :primary_key => :piz_id
  has_many :pedido, :foreign_key => :ped_pizz, :primary_key => :piz_id


end

app/models/medida.rb
class Medida < ApplicationRecord
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :estado, :foreign_key => :ped_esta, :primary_key => :est_id
  belongs_to :local, :foreign_key => :ped_pizz, :primary_key => :piz_id
  belongs_to :trabajador, :foreign_key => :ped_trab, :primary_key => :tra_rut
  belongs_to :cliente, :foreign_key => :ped_clie,  :primary_key => :cli_id
  has_many :pro_ped, :foreign_key => :prpe_pedi, :primary_key => :ped_id, dependent: :destroy, inverse_of: :pedido

  accepts_nested_attributes_for :pro_ped, allow_destroy: true, reject_if: ->(attrs) { attrs['prpe_cant'].blank? || attrs['prpe_prod'].blank? }
end

app/models/pro_ped.rb
class ProPed < ApplicationRecord
  belongs_to :producto, :foreign_key => :prpe_prod, :primary_key => :pro_id
  belongs_to :pedido, :foreign_key => :prpe_pedi, :primary_key => :ped_id
end

app/models/producto.rb
class Producto < ApplicationRecord
  belongs_to :tipo_producto, :foreign_key => :pro_tpro, :primary_key => :tpro_id
  has_many :ins_pro, :foreign_key => :inpr_prod, :primary_key => :pro_id, dependent: :destroy, inverse_of: :producto
  has_many :pro_ped, :foreign_key => :prpe_prod, :primary_key => :pro_id

  #accepts_nested_attributes_for :ins_pro, :reject_if => lambda { |b| b[:inpr_insu].blank? }
  accepts_nested_attributes_for :ins_pro, allow_destroy: true, reject_if: ->(attrs) { attrs['inpr_cant'].blank? || attrs['inpr_insu'].blank? }
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :insumo, :foreign_key => :sto_insu, :primary_key => :ins_id
  belongs_to :pizzeria, :foreign_key => :sto_pizz, :primary_key => :piz_id
end

app/models/tipo_producto.rb
class TipoProducto < ApplicationRecord
  has_many :producto, :foreign_key => :pro_tpro, :primary_key => :tpro_id
end

app/models/trabajador.rb
class Trabajador < ApplicationRecord
  belongs_to :local, :foreign_key => :tra_pizz, :primary_key => :piz_id
  belongs_to :tipo_trabajador, :foreign_key => :tra_ttra, :primary_key => :ttra_id
  has_many :pedido, :foreign_key => :ped_trab, :primary_key => :tra_rut
  belongs_to :account

  validates :tra_rut, uniqueness: true

  before_validation :crearcuenta

  def crearcuenta
    @trabemail= self.tra_nomb+"@pizzacto.cl"
    @acctrab = Account.create(email: @trabemail, password: "password")
    self.account_id = @acctrab.id
  end
end

app/models/v_ins_local.rb
class VInsLocal < ApplicationRecord
end

app/models/v_ven_total.rb
class VVenTotal < ApplicationRecord
end

app/controllers/ins_pros_controller.rb
class InsProsController < ApplicationController
  before_action :set_ins_pro, only: [:show, :edit, :update, :destroy]

  # GET /ins_pros
  def index
    @ins_pros = InsPro.all
  end

  # GET /ins_pros/1
  def show
  end

  # GET /ins_pros/new
  def new
    @ins_pro = InsPro.new
  end

  # GET /ins_pros/1/edit
  def edit
  end

  # POST /ins_pros
  def create
    @ins_pro = InsPro.new(ins_pro_params)

    if @ins_pro.save
      redirect_to @ins_pro, notice: 'Ins pro was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /ins_pros/1
  def update
    if @ins_pro.update(ins_pro_params)
      redirect_to @ins_pro, notice: 'Ins pro was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /ins_pros/1
  def destroy
    @ins_pro.destroy
    redirect_to ins_pros_url, notice: 'Ins pro was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ins_pro
      @ins_pro = InsPro.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def ins_pro_params
      params.require(:ins_pro).permit(:inpr_prod_id, :inpr_insu_id, :inpr_cant)
    end
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/ins_pros_helper.rb
module InsProsHelper
end

app/helpers/insumos_helper.rb
module InsumosHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/ins_pros/_form.html.erb
<%= form_with(model: ins_pro, local: true) do |form| %>
  <% if ins_pro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ins_pro.errors.count, "error") %> prohibited this ins_pro from being saved:</h2>

      <ul>
      <% ins_pro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field col s12 m6 l4">
    <%= form.label :inpr_prod_id %>
    <%= form.text_field :inpr_prod_id, id: :ins_pro_inpr_prod_id %>
  </div>

  <div class="input-field col s12 m6 l4">
    <%= form.label :inpr_insu_id %>
    <%= form.text_field :inpr_insu_id, id: :ins_pro_inpr_insu_id %>
  </div>

  <div class="input-field col s12 m6 l4">
    <%= form.label :inpr_cant %>
    <%= form.number_field :inpr_cant, id: :ins_pro_inpr_cant %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ins_pros/edit.html.erb
<h1>Editing Ins Pro</h1>

<%= render 'form', ins_pro: @ins_pro %>

<%= link_to 'Show', @ins_pro %> |
<%= link_to 'Back', ins_pros_path %>

app/views/ins_pros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ins Pros</h1>

<table>
  <thead>
    <tr>
      <th>Inpr prod</th>
      <th>Inpr insu</th>
      <th>Inpr cant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ins_pros.each do |ins_pro| %>
      <tr>
        <td><%= ins_pro.inpr_prod %></td>
        <td><%= ins_pro.inpr_insu %></td>
        <td><%= ins_pro.inpr_cant %></td>
        <td><%= link_to 'Show', ins_pro %></td>
        <td><%= link_to '<i class="material-icons">mode_edit</i>'.html_safe, edit_ins_pro_path(ins_pro) %></td>
        <td><%= link_to '<i class="material-icons">mode_edit</i>'.html_safe, ins_pro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ins Pro', new_ins_pro_path %>

app/views/ins_pros/new.html.erb
<h1>New Ins Pro</h1>

<%= render 'form', ins_pro: @ins_pro %>

<%= link_to 'Back', ins_pros_path %>

app/views/ins_pros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Inpr prod:</strong>
  <%= @ins_pro.inpr_prod %>
</p>

<p>
  <strong>Inpr insu:</strong>
  <%= @ins_pro.inpr_insu %>
</p>

<p>
  <strong>Inpr cant:</strong>
  <%= @ins_pro.inpr_cant %>
</p>

<%= link_to '<i class="material-icons">mode_edit</i>'.html_safe, edit_ins_pro_path(@ins_pro) %> |
<%= link_to 'Back', ins_pros_path %>