config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :pro_peds
  resources :locals
  resources :tipo_trabajadors
  resources :pedidos
  resources :trabajadors
  resources :stocks
  resources :ins_pros
  resources :clientes
  resources :insumos
  resources :estados
  resources :productos
  resources :tipo_productos
  root 'page#index'
  get 'page/auditoria'
  get 'page/mtb'
  get 'page/procedimiento'
  get 'page/reporte'
  get 'page/vista'
  post 'page/mtb'
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :cliente
  has_one :trabajador
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  attribute :rol, :string, default: "cli"

  after_create :crearcliente

  def crearcliente
    if (self.rol == nil || self.rol == "cli" )
      @clie =Cliente.create(cli_nomb: "Nombre", cli_pass: self.password, account_id:self.id)
      @clie.save
    end
  end
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :pedido, :foreign_key => :ped_clie, :primary_key => :cli_id
  belongs_to :account
end

app/models/estado.rb
class Estado < ApplicationRecord
  has_many :pedido, :foreign_key => :ped_esta, :primary_key => :est_id
end

app/models/ins_pro.rb
class InsPro < ApplicationRecord
  belongs_to :producto, :foreign_key => :inpr_prod, :primary_key => :pro_id
  belongs_to :insumo, :foreign_key => :inpr_insu, :primary_key => :ins_id
end

app/models/insumo.rb
class Insumo < ApplicationRecord
  has_many :ins_pro, :foreign_key => :inpr_insu, :primary_key => :ins_id
  has_many :stock, :foreign_key => :sto_insu, :primary_key => :ins_id
end

app/models/local.rb
class Local < ApplicationRecord
  self.table_name = "pizzeria"
  has_many :stock, :foreign_key => :sto_pizz, :primary_key => :piz_id
  has_many :trabajador, :foreign_key => :tra_pizz, :primary_key => :piz_id
  has_many :pedido, :foreign_key => :ped_pizz, :primary_key => :piz_id


end

app/models/medida.rb
class Medida < ApplicationRecord
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :estado, :foreign_key => :ped_esta, :primary_key => :est_id
  belongs_to :local, :foreign_key => :ped_pizz, :primary_key => :piz_id
  belongs_to :trabajador, :foreign_key => :ped_trab, :primary_key => :tra_rut
  belongs_to :cliente, :foreign_key => :ped_clie,  :primary_key => :cli_id
  has_many :pro_ped, :foreign_key => :prpe_pedi, :primary_key => :ped_id, dependent: :destroy, inverse_of: :pedido

  accepts_nested_attributes_for :pro_ped, allow_destroy: true, reject_if: ->(attrs) { attrs['prpe_cant'].blank? || attrs['prpe_prod'].blank? }
end

app/models/pro_ped.rb
class ProPed < ApplicationRecord
  belongs_to :producto, :foreign_key => :prpe_prod, :primary_key => :pro_id
  belongs_to :pedido, :foreign_key => :prpe_pedi, :primary_key => :ped_id
end

app/models/producto.rb
class Producto < ApplicationRecord
  belongs_to :tipo_producto, :foreign_key => :pro_tpro, :primary_key => :tpro_id
  has_many :ins_pro, :foreign_key => :inpr_prod, :primary_key => :pro_id, dependent: :destroy, inverse_of: :producto
  has_many :pro_ped, :foreign_key => :prpe_prod, :primary_key => :pro_id

  #accepts_nested_attributes_for :ins_pro, :reject_if => lambda { |b| b[:inpr_insu].blank? }
  accepts_nested_attributes_for :ins_pro, allow_destroy: true, reject_if: ->(attrs) { attrs['inpr_cant'].blank? || attrs['inpr_insu'].blank? }
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :insumo, :foreign_key => :sto_insu, :primary_key => :ins_id
  belongs_to :pizzeria, :foreign_key => :sto_pizz, :primary_key => :piz_id
end

app/models/tipo_producto.rb
class TipoProducto < ApplicationRecord
  has_many :producto, :foreign_key => :pro_tpro, :primary_key => :tpro_id
end

app/models/trabajador.rb
class Trabajador < ApplicationRecord
  belongs_to :local, :foreign_key => :tra_pizz, :primary_key => :piz_id
  belongs_to :tipo_trabajador, :foreign_key => :tra_ttra, :primary_key => :ttra_id
  has_many :pedido, :foreign_key => :ped_trab, :primary_key => :tra_rut
  belongs_to :account

  validates :tra_rut, uniqueness: true

  before_validation :crearcuenta

  def crearcuenta
    @trabemail= self.tra_nomb+"@pizzacto.cl"
    @acctrab = Account.create(email: @trabemail, password: "password")
    self.account_id = @acctrab.id
  end
end

app/models/v_ins_local.rb
class VInsLocal < ApplicationRecord
end

app/models/v_ven_total.rb
class VVenTotal < ApplicationRecord
end

app/controllers/pro_peds_controller.rb
class ProPedsController < ApplicationController
  before_action :set_pro_ped, only: [:show, :edit, :update, :destroy]

  # GET /pro_peds
  def index
    @pro_peds = ProPed.all
  end

  # GET /pro_peds/1
  def show
  end

  # GET /pro_peds/new
  def new
    @pro_ped = ProPed.new
  end

  # GET /pro_peds/1/edit
  def edit
  end

  # POST /pro_peds
  def create
    @pro_ped = ProPed.new(pro_ped_params)

    if @pro_ped.save
      redirect_to @pro_ped, notice: 'Pro ped was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /pro_peds/1
  def update
    if @pro_ped.update(pro_ped_params)
      redirect_to @pro_ped, notice: 'Pro ped was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /pro_peds/1
  def destroy
    @pro_ped.destroy
    redirect_to pro_peds_url, notice: 'Pro ped was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pro_ped
      @pro_ped = ProPed.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def pro_ped_params
      params.require(:pro_ped).permit(:prpe_pedi_id, :prpe_prod_id, :prpe_cant)
    end
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/insumos_helper.rb
module InsumosHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/pro_peds_helper.rb
module ProPedsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/pro_peds/_form.html.erb
<%= form_with(model: pro_ped, local: true) do |form| %>
  <% if pro_ped.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pro_ped.errors.count, "error") %> prohibited this pro_ped from being saved:</h2>

      <ul>
      <% pro_ped.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :prpe_pedi_id %>
    <%= form.text_field :prpe_pedi_id, id: :pro_ped_prpe_pedi_id %>
  </div>

  <div class="field">
    <%= form.label :prpe_prod_id %>
    <%= form.text_field :prpe_prod_id, id: :pro_ped_prpe_prod_id %>
  </div>

  <div class="field">
    <%= form.label :prpe_cant %>
    <%= form.number_field :prpe_cant, id: :pro_ped_prpe_cant %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pro_peds/edit.html.erb
<h1>Editing Pro Ped</h1>

<%= render 'form', pro_ped: @pro_ped %>

<%= link_to 'Show', @pro_ped %> |
<%= link_to 'Back', pro_peds_path %>

app/views/pro_peds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pro Peds</h1>

<table>
  <thead>
    <tr>
      <th>Prpe pedi</th>
      <th>Prpe prod</th>
      <th>Prpe cant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pro_peds.each do |pro_ped| %>
      <tr>
        <td><%= pro_ped.prpe_pedi %></td>
        <td><%= pro_ped.prpe_prod %></td>
        <td><%= pro_ped.prpe_cant %></td>
        <td><%= link_to 'Show', pro_ped %></td>
        <td><%= link_to 'Edit', edit_pro_ped_path(pro_ped) %></td>
        <td><%= link_to 'Destroy', pro_ped, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pro Ped', new_pro_ped_path %>

app/views/pro_peds/new.html.erb
<h1>New Pro Ped</h1>

<%= render 'form', pro_ped: @pro_ped %>

<%= link_to 'Back', pro_peds_path %>

app/views/pro_peds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prpe pedi:</strong>
  <%= @pro_ped.prpe_pedi %>
</p>

<p>
  <strong>Prpe prod:</strong>
  <%= @pro_ped.prpe_prod %>
</p>

<p>
  <strong>Prpe cant:</strong>
  <%= @pro_ped.prpe_cant %>
</p>

<%= link_to 'Edit', edit_pro_ped_path(@pro_ped) %> |
<%= link_to 'Back', pro_peds_path %>